### ISSUE TITLE
Current CPU pre-release (v5) crashing

### ISSUE THREAD

**Issue by RivenSkaye** [AmusementClub/vs-dfttest2#4]
Using VapourSynth R59, the current CPU pre-release build crashes as soon as a frame is passed to it on my system.

Windows 10
AMD Ryzen 7 5800H w/ APU

Example code:
```py
den = dfttest2.DFTTest(clip, 0, sigma=9, sigma2=9,
                       tbsize=3, planes=[0, 1, 2])
```
I've tried setting `backend=dfttest2.Backend.CPU`, as well as instantiating CPU with different values for its `opt` arg. I've also tried calling it without arguments other than `clip` and nothing changes the fact that frames pass through the filterchain up until the point it reaches the DFTTest2 call.

Exact same code with the v4 binary and Python script works just fine

**Comment by WolframRhodium** [comment]
Thanks! Please check the latest build.

**Comment by RivenSkaye** [comment]
Latest build fixes it, works like a charm!
